default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: im_bored_development

test:
  <<: *default
  database: im_bored_test

production:
  <<: *default
  database: im_bored_production
  username: im_bored
  password: <%= ENV['IM_BORED_DATABASE_PASSWORD'] %>
